version: "3.5"
services:
  centos7redis5php81:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-msgpack-8.1
  centos8redis5php81:
    volumes:
      - rpms:/home/centos/rpmbuild/SRPMS
      - rpm8:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        image: php-msgpack-8.1

volumes:
  rpms:
    name: rpms
  rpm7:
    name: rpm7
  rpm8:
    name: rpm8
