version: "3"
services:
  centos7redis5:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-msgpack-7.4
  stream8redis5:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        image: php-msgpack-7.4

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream
