version: "3.5"
services:
  centos7redis5php81:
    volumes:
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
        image: php-msgpack-8.1
  centos8redis5php81:
    volumes:
      - rpm8stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS8
        image: php-msgpack-8.1

volumes:
  rpm7:
    name: rpm7
  rpm8stream:
    name: rpm8stream
